SG-22646 Replaced references to Shotgun with ShotGrid
shotgunsoftware/tk-framework-adobe pull request #21
Opened 2021-05-27 15:32 UTC by eshokrgozar

2021-05-28 01:05 UTC, jfboismenu approved these changes
👍 I'm assuming the process to recompile the plugin was well documented then? I don't see any changes to the docs.

2021-05-28 01:05 UTC, jfboismenu commented
@mathurf , your turn!

2021-05-31 14:27 UTC, eshokrgozar commented
> 👍 I'm assuming the process to recompile the plugin was well documented then? I don't see any changes to the docs.

Yeah. So the README has a bunch of information about this. The part that was missing was in [this PR](https://github.com/shotgunsoftware/tk-framework-adobe/pull/18). I'm not sure if we need to fix the timecode thing or just disable it as mentioned in the PR. But it doesn't work with it on.

2021-06-01 18:31 UTC, mathurf requested changes
found this Shotgun mention
![image](https://user-images.githubusercontent.com/8168836/120373155-0198f480-c2e6-11eb-9a23-dd2d7c395107.png)

2021-06-01 19:07 UTC, eshokrgozar commented
> found this Shotgun mention
> ![image](https://user-images.githubusercontent.com/8168836/120373155-0198f480-c2e6-11eb-9a23-dd2d7c395107.png)

fixed

2021-06-02 13:52 UTC, mathurf approved these changes
LGTM

2021-06-02 13:52 UTC, mathurf commented on com.sg.basic.adobe.version
> +v1.1.3
JF told me v1.1.3 is fine

2021-06-02 13:53 UTC, merged